# Generated by Django 5.0.4 on 2024-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sendit', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=955),
        ),
    ]
